# Generated by Django 6.0.6 on 2026-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('none', 'Без категории'), ('anime', 'Аниме'), ('games', 'Игры'), ('movies', 'Фильмы'), ('series', 'Сериалы'), ('manga', 'Манга'), ('books', 'Книги'), ('comics', 'Комиксы'), ('music', 'Музыка'), ('other', 'Другое')], default='none', max_length=20),
        ),
    ]
